apiVersion: v1
kind: ConfigMap
metadata:
  name: email-sender-config
  namespace: logguardian
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka.logguardian.svc.cluster.local:29092
  KAFKA_TOPIC: logs-anomalies-ml
  ALERT_THRESHOLD: "1.3"
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  BATCH_INTERVAL_SECONDS: "900"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-sender
  namespace: logguardian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-sender
  template:
    metadata:
      labels:
        app: email-sender
    spec:
      enableServiceLinks: false
      containers:
        - name: email-sender
          image: europe-west1-docker.pkg.dev/logguardian-497218/logguardian/email-sender:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: email-sender-config
            - secretRef:
                name: monitoring-ui-secrets
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
