apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-model
  namespace: logguardian
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::148761640356:role/LogGuardianMLModelRole
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-model-config
  namespace: logguardian
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka.logguardian.svc.cluster.local:29092
  KAFKA_INPUT_TOPIC: logs-processed
  KAFKA_OUTPUT_TOPIC: logs-anomalies-ml
  KAFKA_GROUP_ID: ml-model
  S3_MODELS_BUCKET: logguardian-models-148761640356
  AWS_REGION: eu-west-1
  LOCAL_MODEL_MODE: "false"
  MODEL_DIR: /app/models
  SEQUENCE_LENGTH: "10"
  DEVICE: cpu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model
  namespace: logguardian
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      serviceAccountName: ml-model
      enableServiceLinks: false
      containers:
        - name: ml-model
          image: 148761640356.dkr.ecr.eu-west-1.amazonaws.com/logguardian/ml-model:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ml-model-config
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
